version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  service-a:
    build: ./service-a
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  service-b:
    build: ./service-b
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
