spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/users_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: redis
  redis:
    host: redis
    port: 6379
